export const bandeirasPaises = {
  "África do Sul": "za" ,
    "Alemanha" : "de" ,
    "Argentina" : "ar" ,
    "Austrália" : "au" ,
    "Brasil" : "br" ,
    "Camarões" : "cm" ,
    "Canadá" : "ca" ,
    "Chile" : "cl" ,
    "China" : "cn" ,
    "Colômbia" : "co" ,
    "Coreia do Norte" : "kp" ,
    "Coreia do Sul" : "kr" ,
    "Dinamarca" : "dk" ,
    "Espanha" : "es" ,
    "Estados Unidos" : "us" ,
    "França" : "fr" ,
    "Holanda" : "nl" ,
    "Inglaterra" : "gb-eng" ,
    "Itália" : "it" ,
    "Jamaica" : "jm" ,
    "Japão" : "jp" ,
    "Marrocos" : "ma" ,
    "Nigéria" : "ng" ,
    "Noruega" : "no" ,
    "Rússia" : "ru" ,
    "Suécia" : "se" ,
    "Suíça" : "ch" ,
    "Tailândia" : "th" ,
    "Taipé Chinesa" : "tw" ,
    "Zâmbia" : "zm", 
}

export default bandeirasPaises;