export const listaPaises = [
  { nome: "África do Sul", codigo: "za", cores: { bg: "#007749", text: "#FFB81C" } },
  { nome: "Alemanha", codigo: "de", cores: { bg: "#FFFFFF", text: "#111111" } },
  { nome: "Argentina", codigo: "ar", cores: { bg: "#75AADB", text: "#FFFFFF" } },
  { nome: "Austrália", codigo: "au", cores: { bg: "#FFCD00", text: "#004B87" } },
  { nome: "Brasil", codigo: "br", cores: { bg: "#FDE047", text: "#1C8144" } },
  { nome: "Camarões", codigo: "cm", cores: { bg: "#007A5E", text: "#FFD100" } },
  { nome: "Canadá", codigo: "ca", cores: { bg: "#FF0000", text: "#FFFFFF" } },
  { nome: "Chile", codigo: "cl", cores: { bg: "#D52B1E", text: "#FFFFFF" } },
  { nome: "China", codigo: "cn", cores: { bg: "#EE1C25", text: "#FFDE00" } },
  { nome: "Colômbia", codigo: "co", cores: { bg: "#FCD116", text: "#003893" } },
  { nome: "Coreia do Norte", codigo: "kp", cores: { bg: "#ED1C24", text: "#FFFFFF" } },
  { nome: "Coreia do Sul", codigo: "kr", cores: { bg: "#C60B1E", text: "#FFFFFF" } },
  { nome: "Dinamarca", codigo: "dk", cores: { bg: "#C60B1E", text: "#FFFFFF" } },
  { nome: "Espanha", codigo: "es", cores: { bg: "#C60B1E", text: "#FFC400" } },
  { nome: "Estados Unidos", codigo: "us", cores: { bg: "#FFFFFF", text: "#002868" } },
  { nome: "França", codigo: "fr", cores: { bg: "#002654", text: "#FFFFFF" } },
  { nome: "Holanda", codigo: "nl", cores: { bg: "#FF4F00", text: "#FFFFFF" } },
  { nome: "Inglaterra", codigo: "gb-eng", cores: { bg: "#FFFFFF", text: "#CE1124" } },
  { nome: "Itália", codigo: "it", cores: { bg: "#0055A5", text: "#FFFFFF" } },
  { nome: "Jamaica", codigo: "jm", cores: { bg: "#009B3A", text: "#FFD100" } },
  { nome: "Japão", codigo: "jp", cores: { bg: "#000555", text: "#FFFFFF" } },
  { nome: "Marrocos", codigo: "ma", cores: { bg: "#C1272D", text: "#006233" } },
  { nome: "Nigéria", codigo: "ng", cores: { bg: "#008751", text: "#FFFFFF" } },
  { nome: "Noruega", codigo: "no", cores: { bg: "#BA0C2F", text: "#FFFFFF" } },
  { nome: "Rússia", codigo: "ru", cores: { bg: "#D52B1E", text: "#FFFFFF" } },
  { nome: "Suécia", codigo: "se", cores: { bg: "#FECC00", text: "#005293" } },
  { nome: "Suíça", codigo: "ch", cores: { bg: "#D52B1E", text: "#FFFFFF" } },
  { nome: "Tailândia", codigo: "th", cores: { bg: "#00247D", text: "#FFFFFF" } },
  { nome: "Taipé Chinesa", codigo: "tw", cores: { bg: "#00247D", text: "#FFFFFF" } },
  { nome: "Zâmbia", codigo: "zm", cores: { bg: "#198A00", text: "#FF7A00" } }
]

export default listaPaises;